### PR TITLE
Update bandage.sqf

### PR DESCRIPTION
**Pull request by Mikeeeyy**

### CODE REVIEW

**Comment by vbawol** [comment]
I guess this was the wrong var?

**Comment by Mikeeeyy** [comment]
Yeah it is the incorrect var, I would give you a bit more detail as to why but I can't remember since it was like 2 weeks ago.

**Comment by Windmolders** [comment]
Has this been tested?

**Comment by Mikeeeyy** [comment]
My medical stats from database after zombies attacked me:
```
[false,false,false,true,false,false,true,9631.67,["aimpoint","relbow","RightFoot","LeftFoot"],[0.475225,0],0,[7.19879,2.7822]]
```
bandage.sqf currently uses:
```
USEC_woundHit 	= [
	"",
	"body",
	"hands",
	"legs",
	"head_hit"
];
```
I made a pull request to change it to:
```
USEC_typeOfWounds = [
	"Pelvis",
	"aimpoint",
	"lelbow","relbow",
	"RightFoot","LeftFoot",
	"neck","pilot"
];
```

**Comment by Windmolders** [comment]
Searched for all refernces in repo ( got 3 hits)

Image of Repo

**Pull request merged**
