### PR TITLE
Small trader changes

### PR DESCRIPTION
**Pull request by AirwavesMan**
Moving mixed oil to building supplies and removing GPS, Range Finder and Night Vision from buylist. These items should be rare items and harder to find than other items.

### CODE REVIEW

**Comment by ebaydayz** [comment]
On a related note, what does everyone think about adding the other SCARs (mk16 and mk17) to the loot tables and traders (except for the TWS of course)? Not sure why, but right now the only one there is the SCAR_H_LNG_Sniper_SD.

**Comment by ndavalos** [comment]
@ebaydayz I usually have those weapons on my servers. Most of my servers are overpoch though lol.

**Comment by oiad** [comment]
@ebaydayz I agree with ndavalos, I normally turn those weapons on my self as well

**Comment by AirwavesMan** [comment]
Totally agree, Ive added the Mk17 mags with re-combine already.

**Comment by AirwavesMan** [comment]
Ive added a few more weapons:

Mk16 Aimpoint SD 
Mk16 CQC 
Mk16 CQC EOTech 
Mk16 EGLM EOTech,(40mm)
Mk16 EGLM RCO,(40mm)
Mk16 EOTech 
Mk16 Mk4CQ/T
Mk16 EGLM EOTech 
Mk17 Sniper
Mk17 Aimpoint
Mk17 Aimpoint SD 
Mk17 EGLM ACOG,(40mm)
L85A2 ACOG
L86A2 ACOG LMG
AA12 Military Shotgun

Is everyone fine with the list?

**Comment by oiad** [comment]
Looks good to me man. Admins will no doubt customize their own lists but it's great to have them there from the getgo.

**Pull request merged**
