### PR TITLE
RedRyder Updated

### PR DESCRIPTION
**Pull request by arma2WillRobinson**
This fixes the cloud of smoke that plumed from the barrel when fired, gives more realistic recoil, and adds its own firing sound. It worked with no config errors normally but I haven't tested it with the epoch paths because my GPU took a dump, so there may be some errors. Let me know what comes up, should be simple fixes. Thanks!

### CODE REVIEW

**Comment by ebaydayz** [comment]
Can you upload a binarized config.bin and texHeaders.bin like you have in your pbo version here?
https://github.com/arma2WillRobinson/Red-Ryder/tree/master/PBO

I honestly don't know which tools to use to make those.

**Comment by icomrade** [comment]
If you use BinPbo make sure binarize is checked, if you'r eusing eliteness make sure rapify is checked in the options menu, if you're using MakePBO you can execute the following in a .bat file.
`%EXE% -B -U -X="thumbs.db,*.h,*.cpp,*.bak,*.png,*.dep,*.log" -P "%REPO_PATH%redryder" %OUT_PATH_ADDONS%`

Note: -U allows unbinarized .p3d files, I believe the only program that can binarize .p3d files is BinPBO so it would be best to use that.

You will not see the .bin file when you extract a .pbo since the program extracting the pbo usually also derapifys the .bin files to their respective .cpp files.

**Comment by arma2WillRobinson** [comment]
No problem, https://github.com/arma2WillRobinson/Red-Ryder/tree/master/BIN I just use BinPBO

**Comment by arma2WillRobinson** [comment]
Woops just rust realized I those were the wrong files, just re uploaded with the correct ones.

**Comment by ebaydayz** [comment]
Ok, thanks. I binarized the whole folder with BinPBO using:
<pre>BinPBO.exe C:\pathto\redryder C:\pathto\Desktop\binarized -WINDOW -BINARIZE -DEBUG -PREFIX z\addons\redryder</pre>

The gun and magazine work fine in game now, but I'm getting path errors for the gear pictures. It may just be me packing the pbo incorrectly:
<pre>Warning Message: Picture equip\w\w_z\addons\redryder\textures\redryder_picture.paa.paa not found
Warning Message: Picture equip\m\m_z\addons\redryder\textures\bb_magazine_picture.paa.paa not found</pre>

**Comment by arma2WillRobinson** [comment]
Wierd, try using this .pbo I just packed myself https://github.com/arma2WillRobinson/Red-Ryder/tree/master/PBO

**Comment by ebaydayz** [comment]
Confirmed same two errors using the pbo you just uploaded to your repo. The gear library description icon loads, but the primary gear picture for the gun and magazine do not.

**Comment by arma2WillRobinson** [comment]
Ok, you might have to remove ".paa" from picture="z\addons\redryder\textures\bb_magazine_picture.paa";  and
picture="z\addons\redryder\textures\redryder_picture.paa"; in the config.cpp.

**Comment by ebaydayz** [comment]
With the .paa removed in config.cpp I now get:
<pre>Warning Message: Picture equip\w\w_z\addons\redryder\textures\redryder_picture.paa not found
Warning Message: Picture equip\m\m_z\addons\redryder\textures\bb_magazine_picture.paa not found</pre>
So it solved the problem of the extra .paa on the end, but the prefix is still incorrect for some reason.

**Comment by icomrade** [comment]
Try appending a \ to the beginning of the path for picture

**Comment by arma2WillRobinson** [comment]
I think icomrade is right, that should solve it.

**Comment by ebaydayz** [comment]
That fixed the RPT errors and the magazine gear picture loading, but now I can't pick up the gun. If I force add it to my inventory it doesn't show in my gear or hands at all. Weird, because the only change I made was to add the ' \ ' on those two picture lines in config.cpp, and the gun was working before.

I then tried adding a ' \ ' in front of all the paths in the config.cpp and their respective file extensions on the end of each one. The result is the same as I just mentioned though.

redryder2

I tried updating the Faces paths in RedRyder.p3d and bb_magazine.p3d as well. It didn't help. Maybe there are some other paths that need to be updated too, I'm not that familiar with Oxygen:
model

**Comment by arma2WillRobinson** [comment]
Hmm, now that's strange. It shows up on the ground but you cant pick it up, and it doesn't show up in your hands, Is the character in holding weapon stance when you force add it to inventory? Also could you post your current config.cpp.

**Comment by ebaydayz** [comment]
Correct, character does not do weapon holding stance and the gun does not show in gear at all. It is definitely occupying the primary slot though.

Currently using the latest from this repo. Only changes are L64 and L104:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/redryder/config.cpp#L64
Changed to:
<pre>picture ="\z\addons\redryder\textures\bb_magazine_picture";</pre>
and:
<pre>picture = "\z\addons\redryder\textures\redryder_picture";</pre>
respectively. Also tried with .paa on and off.

**Comment by arma2WillRobinson** [comment]
Have you tried reverting :
`picture = "\z\addons\redryder\textures\redryder_picture";`
back to:
`picture = "z\addons\redryder\textures\redryder_picture";`
just to confirm that is definitely the cause of the problem.

I've haven't seen that happen with it before, so can you access it as gear on the ground but just can't move it over to your character? I don't think it could be a model path issue because then it wouldn't show up on the ground. You could also try this .pbo to be sure its not a packing problem: https://github.com/arma2WillRobinson/Red-Ryder/tree/master/PBO

**Comment by ebaydayz** [comment]
The pbo you just uploaded works 100% with no errors.

If you can submit a pull that syncs whatever changes you made in that one with the current master that would be great. I'll include that pbo in the test build for next update and enable it in the loot tables.

**Comment by arma2WillRobinson** [comment]
Awesome! The only changes made were adding the "\" to line L64 and L104 so it must have just been some packing issue.

**Comment by arma2WillRobinson** [comment]
On a side note, would you guys have any interest in another weapon I did a couple months ago, here's the armaholic page: http://www.armaholic.com/page.php?id=30175 

I've gotten a lot of interest from people wanting to use it on epoch. If it was to be added in the spawn probability would have to be really low to avoid any balance problems. But I think it could be seen as a rare treasure item.

I could give you a .pbo with epoch paths if you're interested trying it out.

**Comment by ebaydayz** [comment]
That is a very sexy looking weapon @arma2WillRobinson. Nice work.

Generally more options is always better. I don't know about adding it to the loot tables, but it is a nice option to have, like the AS50. Admins may choose to add it, or use it for something special on their server, even if it is not included in the loot tables or traders by default.

Ultimately it is up to @vbawol since this is his repo. I can ask on discord if he doesn't respond here.

**Comment by arma2WillRobinson** [comment]
Thanks very much, you're probably right about the loot tables, would be best to leave it to individual server admins.

**Comment by ebaydayz** [comment]
@arma2WillRobinson vbawol's response on discord:

> 
Sure why not add it if there are no major issues with it. and making it optional as a spawn sounds like a good idea.

So feel free to submit a pull with it if you like, and I can test it out.

**Comment by arma2WillRobinson** [comment]
Cool @ebaydayz here's a 'should work fine' test .pbo: https://github.com/arma2WillRobinson/Anzio-20mm/tree/master/TestPBO
the paths are `z\addons\anzio` so it should just go in the addons folder same as the redryder.pbo
After its tested and confirmed working i'll submit a pull  with the non-binarized pbo contents.

**Comment by ebaydayz** [comment]
I don't see any problems with it in game or RPT. I added it to the addons lists.
https://github.com/EpochModTeam/DayZ-Epoch/commit/bb66b4446c25885469b03c697597003beb5a87a1

**Comment by arma2WillRobinson** [comment]
Problem free imagine that haha. Actually since it's working fine there's really no reason to pull the unbinarized file, would just add clutter.

**Comment by ebaydayz** [comment]
@arma2WillRobinson - Ok, I'll include the binarized one you linked in the next test build .zip.

**Comment by ebaydayz** [comment]
@arma2WillRobinson I just noticed the Anzio weapon slot is type=5; in its config.cpp CfgWeapons.

This does not appear to cause any problems for the gear dialog, but it can for scripts which rely on it. Is it okay if we set it to type=1 (primary) for Epoch? Or is there some reason it needs to be type=5? There are currently no other DayZ or Epoch weapons with type=5. 

Also, are you able to repack the binarized pbo with that change? I don't want to mess it up. Thanks.

**Comment by ebaydayz** [comment]
On second thought we may want to keep it as type 5 (occupying both backpack and primary slots), since it is even more powerful than the AS50 or M107.

**Comment by arma2WillRobinson** [comment]
Yea, I though type 5 was proper because of how large it is, but then again backpacks in Arma have never been very realistic with what can fit inside. So I could go either way, i'll add a second pbo with type=1 to my Anzio repo so you have the option.

**Comment by ebaydayz** [comment]
Alternatively, we can just add a _DZ version and admins can choose which one they want to use. That would be consistent with the way the as50, ksvk, etc. are handled:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgWeapons/Weapon/Sniper/AS50.hpp
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgWeapons/Weapon/Sniper/KSVK.hpp

**Comment by arma2WillRobinson** [comment]
Good idea, that seems to be the best option.

**Pull request merged**
