### PR TITLE
Adding many new skins

### PR DESCRIPTION
**Pull request by AirwavesMan**
I took the chance to add many new skins to the epoch base. It feels better when you are able to loot them in buildings. Ive tested all of them over three times. Every skin works and took damage. If anybody knows a problem with any skin of the list let me know. Some skins of Arma have special abilities like healing or repairing stuff. I could not find anything of that on the new skins. 

I think I changed all files that are necessary.

Skins Ive added:

USMC_Soldier_Officer
USMC_Soldier_MG
USMC_Soldier_Pilot
FR_TL
FR_R
FR_Marksman
FR_Assault_R
RU_Soldier
RU_Soldier_Officer
RUS_Soldier1
RUS_Commander
MVD_Soldier
Ins_Soldier_2
Ins_Commander
Ins_Soldier_Crew
CDF_Soldier
Doctor
Assistant
Worker1
Worker3
Worker4
TK_CIV_Takistani01_EP1
TK_CIV_Takistani03_EP1
TK_CIV_Takistani04_EP1
TK_CIV_Takistani06_EP1
TK_GUE_Soldier_EP1
TK_INS_Soldier_AR_EP1
CZ_Soldier_SL_DES_EP1
US_Soldier_EP1
UN_CDF_Soldier_Guard_EP1
UN_CDF_Soldier_EP1
GER_Soldier_TL_EP1
BAF_Soldier_Officer_MTP
BAF_Soldier_N_MTP

### CODE REVIEW

**Comment by ebaydayz** [comment]
Looks good.

If any of them still get the action to "Heal at xxx" when looking at soldiers, ambulance vehicles or first aid tents you can add `attendant = 0;` to their class in CfgVehicles. But it shouldn't be needed since those actions are already hidden in CfgActions here:

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgArma.hpp#L2-L28

**Comment by AirwavesMan** [comment]
I tried to add the skin FR_Sapper but it has the repair option. I cant disable it and attendant = 0; does not work. The repair option is still there.

class FR_Sapper;
class FR_Sapper_DZ: FR_Sapper {
	displayName = "Camo Sapper";
	attendant = 0;
	side = 1;
	weapons[] = {"Throw","Put"};
	backpack = "";
	magazines[] = {};
	respawnWeapons[] = {"Throw","Put"};
	respawnMagazines[] = {};
	weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
	canHideBodies = 1;
	canCarryBackPack = 1;
};

**Comment by ebaydayz** [comment]
It looks like for that you need to add:
```sqf
class RepairVehicle: None { show = 0; };
```
To CfgActions where I linked. But it is already commented out below that. It should be safe to add, but you should test it out to be sure. I don't think DayZ uses that Arma action for anything, since it adds its own repair action in fn_selfActions.

**Comment by AirwavesMan** [comment]
Thx that worked good. Everything worked as expected.

**Pull request merged**
