### PR TITLE
Update Russian translations

### PR DESCRIPTION
**Pull request by dreamforceinc**

### CODE REVIEW

**Comment by dreamforceinc** [comment]
"STR_EPOCH_KILOTOBACCO_DESC"
"STR_EPOCH_KILOBLACKTEA_DESC"
"STR_EPOCH_TOBACCO_LEAF_DESC"
Is this not a description?

**Comment by dreamforceinc** [comment]
And one more question: "Oil barrel" - what is meant? Engine's oil or a petroleum?

**Comment by ebayShopper** [comment]
Yes, they are descriptions, but since they are incomplete sentences they should not have periods.

I know the other descriptions in the stringtable are mixed right now. Some are fragments and others are complete sentences. Some have periods and some do not, but no period for fragments is a good convention to follow.

The "Oil barrel" is for petroleum.

**Comment by dreamforceinc** [comment]
Can I get examples of that sentences? Maybe I will need to change the translation.

**Comment by ebayShopper** [comment]
I don't know which type of oil @AirwavesMan wanted this to be.

It's the same model and picture as `ItemFuelBarrel`
https://epochmod.gamepedia.com/A2Epoch:Fuel_Barrel

"Fuel" is a less specific word. In this case we are just using it to describe a source of energy which powers vehicles.

I assume "Oil" in this case refers to crude oil or oil used in ships/furnaces. It is not important, just make sure it is different from this translation so they can be distinguished in the gear menu:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/stringtable.xml#L14561-L14563

**Comment by dreamforceinc** [comment]
ok, then I'll leave it as it is.

**Pull request merged**
